### ISSUE TITLE
Version 2.0.2 from npmjs is crashing some devices with Android 10, on startup.

### ISSUE THREAD

**Issue by Chadori** [apache/cordova-plugin-network-information#122]
# Bug Report

## Problem
Version [2.0.2 from npmjs](https://www.npmjs.com/package/cordova-plugin-network-information) is crashing some devices with Android 10, on startup.

### What is expected to happen?
Run on Android Studio. You can also reproduce from the AVD Emulator **(Android 10, Pixel3A)**.

### What does actually happen?
Crashes on startup.

## Information

```
Uncaught exception from plugin:
Connectivity Service : Neither user 10381 nor current process has android.permission.ACCESS_NETWORK_STATE
```
![image](https://user-images.githubusercontent.com/31282960/87260596-57558a00-c4e5-11ea-8c0c-065bf28c7369.png)

Possible similar case: https://stackoverflow.com/questions/24552015/java-lang-securityexception-connectivityservice-neither-user-10134-nor-current

### Environment, Platform, Device

Android 10, Pixel 3A.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
What is your target SDK (or if you don't explicitly set it, what is your version of `cordova-android`)?

**Comment by Chadori** [comment]
Hi, 

Here are the build versions.
```
Cordova-Android : 8.1.0
android-minSdkVersion: 28
android-targetSdkVersion: 28
```

Thank you.

**Comment by breautek** [comment]
Hmm, I'm not reproducing this with a simple cordova app on an android 10 emulator.

It looks like for some reason, your app is missing the `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` declaration in your `AndroidManifest.xml` file. This is something the plugin adds on installation.

Can you confirm that line exists inside `<project-root>/platforms/android/app/src/main/AndroidManifest.xml`? It should appear as a child of the `<manifest>` tag somewhere.

**Comment by Chadori** [comment]
Got it, I will confirm. Thanks.

**Comment by Chadori** [comment]
Hi again,

Yes, I can confirm it has that permission.
It seems I can reproduce if I run it on `Pixel 3A - API29` but not on `Pixel 3A - API 28` even after changing the `target-sdk` to `29`.
![image](https://user-images.githubusercontent.com/31282960/87265937-904a2a80-c4f6-11ea-8edf-2a090a441235.png)

Can you confirm? Thanks.

**Comment by breautek** [comment]
Nope, I still do not experience a device crash on a Pixel 3A, using a simple test app that alerts on network change (which it fires once on launch).

Previously I tested on an existing emulator I had, which was based on Pixel 2, but I'm pretty sure these are just skins and don't actually change the behaviour of the app (other than screen resolutions and some other technical details like total memory)

It's weird that you see the permission tag inside `AndroidManifest.xml` but having an error that suggest your app doesn't have that permission.

The next thing I'd confirm is if your apk actually has those permissions listed.  You can check this by using the `aapt` tool:

`aapt d permissions <path/to/apk>`

You may need to add the android build tools to your path in order to use `aapt`. The executable should be located at: `$ANDROID_HOME/build-tools/29.0.2/`

Note that your build tools version may vary.

The expected output of the `aapt` command above should be something like:
```
$ aapt d permissions app-debug.apk 
package: com.bt.network
uses-permission: name='android.permission.INTERNET'
uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
```

If `ACCESS_NETWORK_STATE` is missing, then there is something happening between writing the `AndroidManifest.xml` and actually building the apk. Or the `AndroidManifest.xml` is improper. If this is the case, we'd need to see if we can build a sample reproduction app that includes the minimal amount of configuration necessary to reproduce the problem. Since I haven't been able to reproduce it myself, it seems likely there might be another plugin causing a conflict.

Here's a list of others things you can try:
- Reinstalling the the plugin and/or the platform
- Updated android sdk/build tools. Since you're using cordova-android@8/ android sdk 28, you should be using build tools 28.
- Consider upgrading to cordova-android@9 & updating  android sdk to 29 / build tools 29

**Comment by breautek** [comment]
Let me know if this issue can be closed.

If not, then I think we'll need a [sample reproduction app](https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md) to continue.

**Comment by Chadori** [comment]
Since I'm not sure what's causing this yet, I'll just close this and make a new thread if any case there is really something wrong.
Thanks.
