### ISSUE TITLE
How to install specific version?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-plugin-network-information#135]
Hallo guys!

if I do `cordova plugin add cordova-plugin-network-information@3.0.0` then in `package.json` I see only 
![image](https://user-images.githubusercontent.com/2271337/129460517-ea91be15-fdf2-4a2d-8cc4-b7c9f0d49033.png)

and `package-lock.json` doesn't contain any information of plugin version

only if I downgrade plugin to `v2.0.2` it will be added to the dependencies list and in `package-lock` file.

**Comment by jimbergman** [comment]
Hi, this is something that often happens when changing the version of something in your config.xml, like when you update to a newer version of a plugin.

In your example, you are updating cordova-plugin-network-information from v2.0.2 to v3.0.0

The problem is this change doesn't get put into the package.json and package-lock.json files.

The solution is what I call a `platform nuke`:

You delete these folders: `node_modules`, `platforms`, `plugins` and the files `package.json` and `package-lock.json`

Then you recreate these folders and files by doing a `cordova platform add ios` and/or `cordova platform add android`

This way the versions specified in `config.xml` are downloaded, and you avoid the build using outdated versions of code previously pulled.

**Comment by breautek** [comment]
Cordova actually caches plugins into the `plugins/` folder and will reuse that (stupidly imo) if the plugin already exists there, even if it's not the requested version.

`cordova plugin remove <plugin>` and reinstalling a different version will update the plugin.

I wouldn't recommend deleting `package.json` though... that contains information that isn't reconstructed.

If you want to nuke and rebuild from a clean slate you'd delete:

- node_modules/
- package-lock.json
- platforms/
- plugins/

Then

```
npm install
cordova platform add <your-platform>
```
