### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by MrWeezle** [apache/cordova-plugin-network-information#83]
Hello,

i am tring to integrate a network check to my ionic app, so I can do work when the device has internet connection. The problem that I have is, that the app (browser and android) crashes with the following error:

> logger.ts:67 TypeError: Object(...) is not a function
    at Network.onConnect (index.js:62)
    at MyApp.webpackJsonp.820.MyApp.manageNetworkConnection (app.component.ts:251)
    at app.component.ts:205
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (core.js:4760)
    at t.invoke (polyfills.js:3)
    at r.run (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)

My code is as follows:

    import { Network } from '@ionic-native/network/ngx';
    
    constructor(private network: Network) {

        this.platform.ready().then(() => {
            this.manageNetworkConnection();
        }
    }
    
    manageNetworkConnection() {
        //Watch for a connection
        let connectSubscription = this.network.onConnect().subscribe(() => {
            console.log('network connected!');
            setTimeout(() => {
                console.log('we got a connection, woohoo!');
            }, 3000);
        });
    
        //Watch for disconnecting a network
        let disconnectSubscription = this.network.onDisconnect().subscribe(() => {
            console.log('network was disconnected');
        });
    }

I have to use the "ngx"-part for the import, otherwise it tells me, it "Cannot find name 'Network'".
Does somebody know, how I can fix that problem? I couldn't find anything related to this.

Thanks in advance

**Comment by toddward** [comment]
Having the exact same issues as above.  Any help on this would be appreciated.

**Comment by thibaud-sanchez** [comment]
I've resolved the problem and this is because you use /ngx import.
When you npm install the network plugin it may have install you the 5.0.0, and the v5 is only compatible with Angular 7.1 and Typescript 3.1 as mentioned here : https://github.com/ionic-team/ionic-native/blob/v5/CHANGELOG.md

Try to downgrade plugin to 4.20.0 like this :

`npm uninstall @ionic-native/network`

then
`npm install @ionic-native/network@4.20.0`

And remove ngx in import like this :
`import { Network } from '@ionic-native/network';`

I had the same problem with the keyboard plugin...

**Comment by timbru31** [comment]
I'm closing this issue since it's/was an issue with the ionic-native wrapper, not the plugin itself. The correct place to ask for help is https://github.com/ionic-team/ionic-native/issues :)
